### ISSUE TITLE
Validity expired for MME production certificates

### ISSUE THREAD

**Issue by Sandeep-Sarma** [omec-project/openmme#8] opened 2019-03-18 11:48 UTC
Running s6a app fails with the following error:
` ERROR   - The certificate is expired.`

Possible reason could be the validity of the MME production certificates: (openmme/src/mme-app/conf/mme.cert.pem) 
```
Certificate:
        Validity
            Not Before: Mar 17 14:42:22 2018 GMT
            Not After : Mar 17 14:42:22 2019 GMT
```
Related issue: #2 
This has to be renewed and updated in the repo.

**Comment by vbarate** [comment] 2019-03-18 15:50
This certificate is a reference certificate generated as per current code in hss and its related certificate.
Certificate for HSS and MME can be generated as instructions in c3po readme section "3. Create Diameter Certificates" - https://github.com/omec-project/c3po/blob/master/README.txt. 
Although right step is to add help/instructions to generate and copy certs, as raised in issue https://github.com/omec-project/openmme/issues/2

**Comment by krsna1729** [comment] 2019-03-18 16:12
Duplicate of #2

**Comment by micpez** [comment] 2019-08-23 20:47
This can be closed.

**Closed as not planned** 2024-04-13 00:45 UTC
Labels: duplicate
